spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:3254/houses
  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

cache:
  algorithm-type: LFU
  capacity: 10
  key-field-name: uuid

server.port: 8081
